# -*- coding: utf-8 -*-
"""Sage implementation of S-Box Property Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4l3GY5F-3pW4VWZlFKxvNLAUTd0Byvk
"""

from sage.all import *
from sage.crypto.sbox import SBox

SBOX_VALUES = [
    0x1B, 0x12, 0x23, 0xCD, 0x39, 0x5C, 0xF8, 0x51, 0xB5, 0x28, 0xB2, 0x15, 0xD7, 0x91, 0x97, 0x09,
    0xC4, 0xC7, 0xBF, 0x38, 0x73, 0xBA, 0x94, 0x68, 0x74, 0xEA, 0xE1, 0x25, 0xE9, 0x14, 0xAD, 0xDF,
    0xFE, 0xAC, 0x7C, 0xD1, 0x40, 0x20, 0xB7, 0x31, 0x11, 0x3E, 0x77, 0x42, 0xD6, 0x04, 0x9F, 0x1D,
    0xA6, 0x00, 0x5F, 0xA4, 0xD9, 0xF2, 0x8C, 0x1C, 0xDD, 0xC2, 0x96, 0xA8, 0xC8, 0xFB, 0x70, 0x81,
    0x62, 0xED, 0xCA, 0x88, 0xA2, 0xD2, 0xC1, 0xB0, 0x8B, 0x84, 0xBB, 0x5A, 0x44, 0x82, 0xB1, 0x32,
    0xA1, 0x64, 0x02, 0x3D, 0x24, 0x86, 0x0B, 0xEB, 0x76, 0xEE, 0x9E, 0xD5, 0x50, 0xA5, 0x90, 0x4A,
    0x4E, 0x6C, 0xAB, 0x59, 0x30, 0x8F, 0xCE, 0x18, 0xC5, 0x08, 0x53, 0x69, 0xDA, 0x5B, 0x92, 0xFA,
    0xF0, 0xCB, 0x4B, 0x03, 0x56, 0xC3, 0xFF, 0xE6, 0xCF, 0xD4, 0x55, 0x0E, 0x93, 0xFD, 0x13, 0x1F,
    0x16, 0xEC, 0xE8, 0x17, 0x4F, 0xD8, 0xEF, 0x4C, 0x7B, 0x6F, 0x43, 0x71, 0xC9, 0x1E, 0xF3, 0x87,
    0x6D, 0xBC, 0xDE, 0xA0, 0x75, 0x3F, 0x07, 0xDC, 0xBE, 0x46, 0x6B, 0x37, 0xF1, 0x65, 0x33, 0x7F,
    0xF9, 0xE4, 0xAE, 0x19, 0x2B, 0xF7, 0x80, 0x34, 0x8E, 0x35, 0x5E, 0x3C, 0x2D, 0x89, 0x5D, 0x9C,
    0x26, 0x95, 0x6A, 0xA9, 0x52, 0xC0, 0xF4, 0xD0, 0x83, 0x2F, 0xCC, 0xE2, 0xE3, 0xE7, 0x0F, 0x48,
    0x3A, 0xB6, 0xAA, 0x9B, 0x7D, 0x45, 0x85, 0x2A, 0xB3, 0x8A, 0x58, 0x06, 0x7A, 0xE5, 0xA7, 0x8D,
    0xFC, 0x0A, 0xAF, 0x98, 0x01, 0x79, 0x9D, 0xBD, 0x47, 0x3B, 0x05, 0x41, 0x63, 0xF5, 0x57, 0xB8,
    0xD3, 0x22, 0x4D, 0xB9, 0x0D, 0x2E, 0x29, 0xA3, 0x36, 0x2C, 0x49, 0x99, 0x60, 0x54, 0x6E, 0xDB,
    0x78, 0x9A, 0xF6, 0xC6, 0xB4, 0x0C, 0x1A, 0x27, 0x61, 0x67, 0xE0, 0x72, 0x21, 0x7E, 0x10, 0x66
]

def validate_sbox(values):
    if len(values) == 0 or (len(values) & (len(values) - 1)) != 0:
        raise ValueError("S-box length must be a power of 2.")

    m = int(log(len(values), 2))
    max_output = max(values)
    n = max(1, max_output.bit_length())

    if any(v < 0 for v in values):
        raise ValueError("S-box values must be nonnegative integers.")

    if max_output >= 2**n:
        raise ValueError("Invalid output size.")

    return m, n

def max_matrix_entry_ignoring_first_row_col(M):
    rows = M.nrows()
    cols = M.ncols()
    return max(M[a, b] for a in range(1, rows) for b in range(1, cols))

def print_component_function(S, b):
    if b <= 0 or b >= 2**S.output_size():
        raise ValueError("Component mask b must satisfy 1 <= b < 2^output_size.")

    f = S.component_function(b)
    print("\nComponent function for b = 0x%02X:" % b)
    print("  Algebraic degree:", f.algebraic_degree())
    print("  Nonlinearity:", f.nonlinearity())
    print("  Is bent:", f.is_bent())
    print("  Truth table:", list(f.truth_table()))
    return f

def calculate_min_nonlinearity(S):
    """
    Manually calculates the minimum nonlinearity of the S-box
    by checking every non-zero component function.
    """
    min_nl = float('inf')
    output_space = 2 ** S.output_size()

    # Iterate through all non-zero masks 'b' (1 to 255 for an 8-bit S-box)
    for b in range(1, output_space):
        comp_func = S.component_function(b)
        current_nl = comp_func.nonlinearity()

        if current_nl < min_nl:
            min_nl = current_nl

    return min_nl

def print_coordinate_functions_nonlinearity(S):
    """
    Calculates and prints the nonlinearity for the 8 individual
    coordinate functions of the S-box.
    """
    print("\n--- Coordinate Functions Nonlinearity ---")
    for i in range(S.output_size()):
        mask = 1 << i
        f = S.component_function(mask)
        nl = f.nonlinearity()
        print("Bit %d (Mask 0x%02X): Nonlinearity = %d" % (i, mask, nl))

def main():
    m, n = validate_sbox(SBOX_VALUES)
    S = SBox(SBOX_VALUES)

    print("S-box size: %d x %d" % (S.input_size(), S.output_size()))
    print("Number of entries:", len(SBOX_VALUES))
    print("Is permutation:", S.is_permutation())

    if S.input_size() != 8 or S.output_size() != 8:
        print("Warning: expected an 8 x 8 S-box.")

    print("\nCore cryptographic properties")

    # Compare built-in vs manual minimum nonlinearity
    print("a) nonlinearity() [Built-in]:", S.nonlinearity())
    manual_min_nl = calculate_min_nonlinearity(S)
    print("   -> Explicitly Calculated Min Nonlinearity:", manual_min_nl)

    print("b) is_bent():", S.is_bent())
    print("c) is_almost_bent():", S.is_almost_bent())

    # Check the 8 individual output bits
    print_coordinate_functions_nonlinearity(S)

    BCT = S.boomerang_connectivity_table()
    bct_max_checked = max_matrix_entry_ignoring_first_row_col(BCT)

    print("\nBoomerang & Differential Properties")
    print("d) boomerang_uniformity():", S.boomerang_uniformity())
    print("   BCT max check:", bct_max_checked)
    print("e) boomerang_connectivity_table(): %d x %d matrix generated" % (BCT.nrows(), BCT.ncols()))

    print("f) maximal_difference_probability():", float(S.maximal_difference_probability()))

    f = print_component_function(S, b=0x01)

    print("\nAlgebraic degree properties")
    print("g) max_degree():", S.max_degree())
    print("h) min_degree():", S.min_degree())

    DDT = S.difference_distribution_table()
    ddt_max_checked = max(DDT[a, b] for a in range(1, DDT.nrows()) for b in range(DDT.ncols()))

    print("\nDifferential properties")
    print("i) differential_uniformity():", S.differential_uniformity())
    print("   DDT max check:", ddt_max_checked)

    print("\nExpected full-table objects")
    print("DDT dimensions:", DDT.nrows(), "x", DDT.ncols())
    print("BCT dimensions:", BCT.nrows(), "x", BCT.ncols())

    # Printing the full tables
    print("\n--- DIFFERENCE DISTRIBUTION TABLE (DDT) ---")
    print(DDT)

    print("\n--- BOOMERANG CONNECTIVITY TABLE (BCT) ---")
    print(BCT)

if __name__ == "__main__":
    main()